### PR TITLE
Allow functions and typedefs to be declared after use (in upper scope…

### PR DESCRIPTION
**Pull request by magnusjt**
Allow functions and typedefs to be declared after use (in upper scope only).

This means that it still picks up the definite errors, while still allowing us to define stuff after use, as long as the usage is in a lower scope.

### CODE REVIEW

**Comment by lostfields** [comment]
I think we should keep it as it is since it may tell you that you have done something wrong. This rule will maybe avoid writing code like this:

```javascript
const selector = () => {
  return {
    selected: getSelected(),
    today: getToday()
  }
}

if( selector().selected.lenght == 0) { // error
}

const getSelected = () => {
  return []
}

const getToday = () => {
  return new Date()
}
```

with this rule you will get notified that you are using `getSelected` and `getToday` before definition, and it may result in an error, especially if the method `selector` is used before `getSelected` and `getToday` is defined.

if you define `getSelected` and `getToday` as functions instead of constants you will not get warning, and the above code will work.

**Comment by magnusjt** [comment]
Yes, would be better if we could only allow arrow functions, and not all variables. Until then, we can just close this pr.

**Comment by lostfields** [comment]
@magnusjt for the record, arrow functions has to be assigned variables to be used later, that's why this rule is important.

**Comment by magnusjt** [comment]
I know, but as with normal functions, if they're defined in the top scope the intent is usually not to call them in that same scope (unless you're doing a script and/or dealing with global variables etc). I guess I just wanted to define my arrow functions the same as regular functions..

**Pull request closed without merging**
